/* EXAMPLE INTERFACE */

// TODO: WRITE CODE HERE

/* EXAMPLE CLASS */
/* EXAMPLE ENCAPSULATION */

// TODO: WRITE CODE HERE

/* EXAMPLE HERITAGE */
/* EXAMPLE OVERRIDE */

// TODO: WRITE CODE HERE

/* EXAMPLE GENERIC */

// TODO: WRITE CODE HERE

/* EXAMPLE CLASS INSTANTIATION */

// TODO: WRITE CODE HERE

/* EXAMPLE CLASS METHOD INVOCATION */

// TODO: WRITE CODE HERE

/* EXAMPLE POLYMORPHISM */

// TODO: WRITE CODE HERE

/* CREATE SOME CLASSES FOR GENERICS EXAMPLE */

// TODO: WRITE CODE HERE

/* EXAMPLE GENERIC USAGE */

// TODO: WRITE CODE HERE

/* EXAMPLE COMPARISON METHOD */

// TODO: WRITE CODE HERE

/* EXAMPLE DIFFERENCE OF COMPARING EQUALITY WITH COMPARING OBJECT IDENTIFIERS */

// TODO: WRITE CODE HERE

/* EXAMPLE PUBLIC SETTERS AND GETTERS FOR PRIVATE VARIABLES */

// TODO: WRITE CODE HERE
